### ISSUE TITLE
Assertion error while generating updates

### ISSUE THREAD

**Issue by wolfgang42** [wolfgang42/vagrant-deb#10]
Updates stopped on 2018-01-29; the failure is as follows:
```
Traceback (most recent call last):                                                                                                                                                                                               
  File "/app/build-packages.py", line 35, in <module>                                                                                                                                                                            
    sys.stdout.write(releaseinfo.build_control_entry(build, 'control'))                                                                                                                                                          
  File "/app/releaseinfo.py", line 70, in build_control_entry
    build_control_file(build)
  File "/app/releaseinfo.py", line 15, in wrapper
    result = getresult(*args)
  File "/app/releaseinfo.py", line 51, in build_control_file
    assert head[36:56] == '0     0     100644  ' # Owner, group, mode
AssertionError
```

**Comment by wolfgang42** [comment]
Seems to be some sort of difference in the file-mode of the ar header, which I heavily assert to make sure that any changes will be kicked out immediately instead of causing problems to sneak in.

In this case, previous packages all had mode `100644` whereas 2.0.2 just has `644`. I'm not entirely clear on why this would have changed but for our purposes it doesn't matter, so I'm going to just patch the program to accept either one.
